/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package PreviewTabelPage;

import com.sun.jdi.connect.spi.Connection;
import java.beans.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import konektor.connect;
// Pastikan ini sesuai dengan implementasi Anda

/**
 *
 * @author HUSAIN
 */
public class LaporanKeuangan extends javax.swing.JDialog {

    /**
     * Creates new form LaporanKeuangan
     */
    static DefaultTableModel TU = new DefaultTableModel();

    public LaporanKeuangan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        if (TU == null) {
            TU = new DefaultTableModel();
        }

        // Populate and configure the table
        settingTableKeuangan();
        viewdataKeuangan("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_kembali = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pencarianProduk = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_uang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        label_kembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_kembali.setForeground(new java.awt.Color(255, 255, 255));
        label_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_left_2_20px.png"))); // NOI18N
        label_kembali.setText("KEMBALI");
        label_kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_kembaliMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        pencarianProduk.setFont(new java.awt.Font("Rockwell Nova Light", 0, 14)); // NOI18N
        pencarianProduk.setForeground(new java.awt.Color(0, 102, 102));
        pencarianProduk.setText("Pencarian");
        pencarianProduk.setBorder(null);
        pencarianProduk.setSelectionColor(new java.awt.Color(0, 153, 153));
        pencarianProduk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pencarianProdukFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pencarianProdukFocusLost(evt);
            }
        });
        pencarianProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianProdukActionPerformed(evt);
            }
        });
        pencarianProduk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pencarianProdukKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pencarianProdukKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pencarianProduk, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pencarianProduk, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_search_20px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(label_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1026, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(label_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tbl_uang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "ID_Transaksi", "ID_AKUN", "TANGGAL TRANSAKSI", "KODE BARANG", "JUMLAH PRODUK", "TOTAL HARGA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_uang.setRowHeight(40);
        tbl_uang.setSelectionBackground(new java.awt.Color(0, 255, 204));
        jScrollPane1.setViewportView(tbl_uang);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_kembaliMouseClicked
        dispose();
    }//GEN-LAST:event_label_kembaliMouseClicked

    private void pencarianProdukFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pencarianProdukFocusGained
        String Cari = pencarianProduk.getText();
        if (Cari.equals("Pencarian")) {
            pencarianProduk.setText("");
        }
    }//GEN-LAST:event_pencarianProdukFocusGained

    private void pencarianProdukFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pencarianProdukFocusLost
        String Cari = pencarianProduk.getText();
        if (Cari.equals("") || Cari.equals("Pencarian")) {
            pencarianProduk.setText("Pencarian");
        }
    }//GEN-LAST:event_pencarianProdukFocusLost

    private void pencarianProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pencarianProdukActionPerformed

    private void pencarianProdukKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pencarianProdukKeyReleased
        String key = pencarianProduk.getText();
        String where = "WHERE "
                + "kode_produk LIKE '%" + key + "%' OR "
                + "nama_produk LIKE '%" + key + "%' OR "
                + "kategori LIKE '%" + key + "%' OR "
                + "harga_jual LIKE '%" + key + "%' OR "
                + "";
    }//GEN-LAST:event_pencarianProdukKeyReleased

    private void pencarianProdukKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pencarianProdukKeyTyped

        String key = pencarianProduk.getText();
        String query = "SELECT * FROM products WHERE "
                + "kode_produk LIKE ? OR "
                + "nama_produk LIKE ? OR "
                + "kategori LIKE ? OR "
                + "harga_jual LIKE ? OR "
                + "harga_beli LIKE ? OR "
                + "stok LIKE ?";

    }//GEN-LAST:event_pencarianProdukKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LaporanKeuangan dialog = new LaporanKeuangan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_kembali;
    private javax.swing.JTextField pencarianProduk;
    private javax.swing.JTable tbl_uang;
    // End of variables declaration//GEN-END:variables

    public static void viewdataKeuangan(String where) {
        try {
            for (int i = TU.getRowCount() - 1; i >= 0; i--) {
                TU.removeRow(i);
            }
            java.sql.Connection K = konektor.connect.Go();
            java.sql.Statement S = K.createStatement();

            // Construct SQL query (Using prepared statements to avoid SQL injection)
            String Q = "SELECT * FROM transaksi " + where;

            // Execute query
            ResultSet R = S.executeQuery(Q);
            int no = 1;

            // Iterate over the result set and add rows to the table
            while (R.next()) {
                int ID_T = R.getInt("ID_transaksi");
                String ID_A = R.getString("ID_AKUN");
                String TGL = R.getString("tanggal_transaksi");
                String KP = R.getString("kode_produk");
                String JP = R.getString("jumlah_produk");
                String TH = R.getString("total_harga");

                // Add a new row to the table model
                Object[] HKR = {no, ID_T, ID_A, TGL, KP, JP, TH};
                TU.addRow(HKR);
                no++;
            }

            // Close resources
            R.close();
            S.close();
            K.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private void settingTableKeuangan() {
        TU = (DefaultTableModel) tbl_uang.getModel();

        tbl_uang.getColumnModel().getColumn(0).setMinWidth(50);
        tbl_uang.getColumnModel().getColumn(0).setMaxWidth(70);

        tbl_uang.getColumnModel().getColumn(1).setMinWidth(0);
        tbl_uang.getColumnModel().getColumn(1).setMaxWidth(0);

        tbl_uang.getColumnModel().getColumn(2).setMinWidth(350);
        tbl_uang.getColumnModel().getColumn(2).setMaxWidth(500);

        tbl_uang.getColumnModel().getColumn(3).setMinWidth(350);
        tbl_uang.getColumnModel().getColumn(3).setMaxWidth(500);

        tbl_uang.getColumnModel().getColumn(4).setMinWidth(350);
        tbl_uang.getColumnModel().getColumn(4).setMaxWidth(500);

        tbl_uang.getColumnModel().getColumn(5).setMinWidth(350);
        tbl_uang.getColumnModel().getColumn(5).setMaxWidth(500);
    }

}
